/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package woochatapp.register;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import woochatapp.login.Login;

/**
 *
 * @author anton
 */
public class Register extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderRadioButtonGroup = new javax.swing.ButtonGroup();
        Register = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        surnameInputField = new javax.swing.JTextField();
        emailInputField1 = new javax.swing.JTextField();
        masculinRadioButton = new javax.swing.JRadioButton();
        femininRadioButton = new javax.swing.JRadioButton();
        registerButton1 = new java.awt.Button();
        passwordInputField1 = new javax.swing.JPasswordField();
        loginSwitchButton = new java.awt.Button();
        dataNasterii = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Register.setBorder(javax.swing.BorderFactory.createTitledBorder("Register to WooChatApp"));

        nameLabel.setText("Nume");

        surnameLabel.setText("Prenume");

        genderLabel.setText("Sex");

        dateLabel.setText("Data Nasterii");

        emailLabel.setText("Email");

        passwordLabel.setText("Parola");

        nameInputField.setForeground(new java.awt.Color(153, 153, 153));
        nameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputFieldActionPerformed(evt);
            }
        });

        surnameInputField.setForeground(new java.awt.Color(153, 153, 153));

        emailInputField1.setForeground(new java.awt.Color(153, 153, 153));

        genderRadioButtonGroup.add(masculinRadioButton);
        masculinRadioButton.setSelected(true);
        masculinRadioButton.setText("Masculin");
        masculinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinRadioButtonActionPerformed(evt);
            }
        });

        genderRadioButtonGroup.add(femininRadioButton);
        femininRadioButton.setText("Feminin");
        femininRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femininRadioButtonActionPerformed(evt);
            }
        });

        registerButton1.setLabel("Inregistreaza-te");
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });

        passwordInputField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputField1ActionPerformed(evt);
            }
        });

        loginSwitchButton.setLabel("Inapoi la login");
        loginSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSwitchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addComponent(passwordLabel)
                    .addComponent(dateLabel)
                    .addComponent(nameLabel)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameLabel)
                            .addComponent(genderLabel))
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(masculinRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailInputField1)
                                    .addComponent(passwordInputField1)
                                    .addComponent(femininRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataNasterii, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                            .addGroup(RegisterLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(316, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginSwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginSwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabel)
                            .addComponent(surnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(masculinRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femininRadioButton)
                        .addGap(16, 16, 16)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(dataNasterii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailInputField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel)
                            .addComponent(passwordInputField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputFieldActionPerformed

    private void loginSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSwitchButtonActionPerformed
         Login login=new Login();
         login.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_loginSwitchButtonActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed

        boolean OK = true;
        
        try{
            String query = "INSERT INTO sql7287415.users (nume, prenume, sex, datanasterii, email, parola) VALUES (?, ?, ?, ?, ?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://sql7.freesqldatabase.com:3306/sql7287415","sql7287415","eVszZdEM8y");
            pst = con.prepareStatement(query);
            
        try {
                String nume = nameInputField.getText().toString();
                if(!nume.matches("[A-Za-z]+"))
                    throw new Exception();
                pst.setString(1, nume);
            }
            catch(Exception e1) {
                nameInputField.setText("");
                JOptionPane.showMessageDialog(nameInputField,"Va rugam, introduceti un nume valid!");
                OK = false;
            }
        try {
                String prenume = surnameInputField.getText().toString();
                if(!prenume.matches("[A-Za-z]+"))
                    throw new Exception();
                pst.setString(2, prenume);

            }
            catch(Exception e1) {
                surnameInputField.setText("");
                JOptionPane.showMessageDialog(surnameInputField,"Va rugam, introduceti un prenume valid!");
                OK = false;
            }
                String gender = null;
                if(masculinRadioButton.isSelected()==true) gender = "Masculin";
                else gender = "Feminin";
                pst.setString(3, gender);
        try {
                java.util.Date dataDeAfisat = dataNasterii.getDate();
                java.sql.Date dataNasteriiA = new java.sql.Date(dataDeAfisat.getTime());  
                System.out.println(dataNasteriiA.getYear());
                                System.out.println(dataNasteriiA.getDate());

                if(dataNasteriiA.getYear()>=105)
                    throw new Exception();
                pst.setDate(4, dataNasteriiA);
            }
            catch(Exception e1) {
                dataNasterii.setDate(null);
                JOptionPane.showMessageDialog(dataNasterii,"Varsta minima este de 14 ani.");
                OK = false;
            }

        try {
                String email = emailInputField1.getText().toString();
                if(!email.contains("@") && !email.contains("."))
                    throw new Exception();
                pst.setString(5, email);

            }
            catch(Exception e1) {
                emailInputField1.setText("");
                JOptionPane.showMessageDialog(emailInputField1,"Va rugam, introduceti un email valid!");
                OK = false;
            }
        try {
                String parola = passwordInputField1.getText().toString();
                if(parola.length() < 8)
                    throw new Exception();
                pst.setString(6, parola);
//passwordInputField1.getPassword().toString()
            }
            catch(Exception e1) {
                passwordInputField1.setText("");
                JOptionPane.showMessageDialog(passwordInputField1,"Parola trebuie sa contina minim 8 caractere.");
                OK = false;
            }
        
            if(OK==true)
            {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Inregistrarea a fost facuta cu success!");
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_registerButton1ActionPerformed

    private void masculinRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinRadioButtonActionPerformed

    private void femininRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femininRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femininRadioButtonActionPerformed

    private void passwordInputField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputField1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Register;
    private com.toedter.calendar.JDateChooser dataNasterii;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField emailInputField1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JRadioButton femininRadioButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.ButtonGroup genderRadioButtonGroup;
    private java.awt.Button loginSwitchButton;
    private javax.swing.JRadioButton masculinRadioButton;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordInputField1;
    private javax.swing.JLabel passwordLabel;
    private java.awt.Button registerButton1;
    private javax.swing.JTextField surnameInputField;
    private javax.swing.JLabel surnameLabel;
    // End of variables declaration//GEN-END:variables
}
